os:
  - linux
#  - osx

dist: trusty

language: node_js

node_js:
#  - '6'
#  - '5'
#  - '4'
  - '0.12'

#sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libgtk-3-dev
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
