version: 1.0.{build}
image: Visual Studio 2017


environment:
  matrix:
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

test_script:
  - npm test

build: off
